#!/usr/bin/env ruby

require_relative '../lib/website/deployer'

domain = ARGV.shift
if domain.nil?
  puts "Usage: #{File.basename(__FILE__)} {domain}"
  puts "Where name is www.cloudamqp.com or www.cloudmqtt.com etc."
  exit 1
force = ARGV.shift == '--force'
puts "Rendering #{name}"
Website::Deployer.new(domain).render
puts "#{domain} rendered"
